- Cargo.toml
@saschagrunert @haircommander ptal.
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>
> Reduce binary size in release mode

- Cargo.toml
- src/client.rs
@haircommander @saschagrunert ptal
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>
> Add test client binary

- Cargo.lock
- Cargo.toml
- build.rs
- src/config.rs
- src/server.rs
We now do not rely on dependencies any more which we do not actually
use.
> Remove unused dependencies

- .github/workflows/ci.yml
- .github/workflows/gh-pages.yml
- Cargo.lock
- Cargo.toml
- src/config.rs
- src/server.rs
* Adds graceful shutdown logic with a SIGTERM
* fixes a few variables for the command line parser
* adds an address argument
* fixes an issue with the workflows not installing the rust toolchain
> add graceful shutdown

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- tests/integration.rs
This adds a test to verify the maximum amount of RSS used by the server binary.
> Add max rss integration test

- README.md
> README: enhance project goal

- Cargo.lock
- Cargo.toml
- src/client.rs
- src/config.rs
- src/server.rs
- src/stream.rs
This changes the config to point to a UDS instead of a TCP listener.
> Add unix domain socket support

- src/server.rs
If the binary runs in the terminal, then we would like to allow graceful
shutdown in the same way when receiving SIGTERM.
> Listen to SIGINT as well

- .github/workflows/gh-pages.yml
Fixes the failing CI: https://github.com/containers/conmon-rs/runs/4169288653?check_suite_focus=true
> Add rustfmt to gh-pages update job

- Cargo.lock
- Cargo.toml
- src/init.rs
- src/server.rs
```
$ cat /proc/$(pidof conmon-server)/status | grep RSS                                                                                             
VmRSS:      1692 kB
```
> setup oom and locale

- Cargo.toml
- README.md
- src/config.rs
- src/server.rs
Removing the references to gRPC since we're not using it any more.
> Remove gRPC references

- Cargo.lock
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/init.rs
- conmon-rs/server/src/lib.rs
> remove dependency on gettext-rs

- .github/workflows/ci.yml
- conmon-rs/server/src/init.rs
> fixes clippy lint in init.rs

- Cargo.lock
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/cri_logger.rs
- conmon-rs/server/src/lib.rs
This adds the kubernetes log file functionality as dedicated module.
> Implement k8s file logger

- Cargo.lock
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/console.rs
- conmon-rs/server/src/lib.rs
A few TODOs are still open but the basic fd passing works for now.
> Add console socket

- conmon-rs/server/src/console.rs
- conmon-rs/server/src/iostreams.rs
- conmon-rs/server/src/lib.rs
- conmon-rs/server/src/rpc.rs
Playing around with a Pty abstraction to be able to read/write to the master pty.
> Add reading from console pty

- Cargo.lock
- conmon-rs/server/Cargo.toml
We do not have to rely on the master build any more.
> Pin clap to v3.0.12

- Cargo.lock
- conmon-rs/server/Cargo.toml
> Update clap to v3.1.0

- Cargo.lock
- conmon-rs/common/proto/conmon.capnp
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/console.rs
- conmon-rs/server/src/iostreams.rs
- conmon-rs/server/src/lib.rs
- conmon-rs/server/src/rpc.rs
- internal/proto/conmon.capnp.go
- pkg/client/client.go
- pkg/client/client_test.go
> exec sync support

- conmon-rs/server/src/child.rs
- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/rpc.rs
This solves a FIXME in rpc.rs.
> Use `u32` for PID

- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/rpc.rs
- pkg/client/client_test.go
We now use a oneshot channel to pass the exit code if a child is done.
> Set correct exit code on execsync

- conmon-rs/server/src/terminal.rs
This removes the tokio runtime creation and re-uses the already existing one.
> Don't create runtime in `Terminal`

- Cargo.lock
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/container_io.rs
- conmon-rs/server/src/server.rs
- conmon-rs/server/src/streams.rs
Fixes https://github.com/containers/conmon-rs/issues/299
> Fix thread leak in `Streams`

- pkg/client/client_test.go
This reverts commit d8663cfc65658a5253500c8d5f7493c64c4c8ae5.
I did not mean to include it in my other PR
> Revert "test: add stress test for ExecSyncRequests"

- conmon-rs/server/src/container_log.rs
Follow-up on https://github.com/containers/conmon-rs/pull/320, where we
now join the futures instead of waiting for each one.
> Join futures in container_log module

- conmon-rs/server/src/attach.rs
- conmon-rs/server/src/child.rs
- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/container_io.rs
- conmon-rs/server/src/container_log.rs
- conmon-rs/server/src/cri_logger.rs
- conmon-rs/server/src/rpc.rs
- conmon-rs/server/src/streams.rs
- conmon-rs/server/src/terminal.rs
- pkg/client/client_test.go
- pkg/client/suite_test.go
Integrate the attach functionality.
Fixes https://github.com/containers/conmon-rs/issues/287
> Integrate attach

- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/container_io.rs
- conmon-rs/server/src/rpc.rs
- conmon-rs/server/src/server.rs
- conmon-rs/server/src/terminal.rs
We now cleanup some type conversions as well as method signatures.
> Cleanup some types and code

- Makefile
- pkg/client/client_test.go
I think this one has been forgotten.
> Enable non-terminal attach test

- .github/workflows/ci.yml
- .golangci.yml
- go.mod
- pkg/client/attach.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/suite_test.go
We now use golangci-lint and apply some lint fixes.
> Use golangci lint

- conmon-rs/server/src/config.rs
- pkg/client/client.go
- pkg/client/consts.go
- pkg/client/suite_test.go
This enhances the server config usage by adding necessary documentation
as well as a continent function to create the config.
> Add server config docs and validation

- Makefile
- go.mod
- go.sum
- internal/proto/conmon.capnp.go
> vendor: bump to capnp latest head

- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/oom_watcher.rs
We now replace the unwrap code parts with case by case handling.
> Replace `.unwrap`s

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/failing-test.yml
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- Makefile
- OWNERS
We now add a bunch of governance files to that repository.
> Add issue and PR templates

- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/oom_watcher.rs
/kind cleanup
We now apply a bunch of rules, for example:
- Start logs upper case
- Remove redundant information like the PID (already part of the tracing span)
- Do not print "Error" for error logs, since the level already tells us
that it's an error.
None
None
```release-note
None
```
> Sanitize oom watcher logs

- conmon-rs/server/src/child_reaper.rs
/kind cleanup
We actually do not need to return a result because the function is infallible.
None
None
```release-note
None
```
> Make `kill_grandchild` return no `Result`

- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/oom_watcher.rs
- pkg/client/client_test.go
- pkg/client/suite_test.go
/kind ci
I also refactored some logs to automatically trace the PID as well as sanitized them.
None
The new test cases:
```
ConmonClient CreateContainer
should catch out of memory (oom) events with terminal
/home/runner/work/conmon-rs/conmon-rs/pkg/client/client_test.go:135
2022-05-13T09:09:27.337145Z  INFO conmon::server: 166: Received SIGINT
2022-05-13T09:09:27.338161Z  INFO conmon::server: 120: Using stdout logger
2022-05-13T09:09:27.338182Z  INFO conmon::server: 130: Set log level to: debug
2022-05-13T09:09:27.339977Z DEBUG conmon::rpc: 50: Got a version request
2022-05-13T09:09:27.340533Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}: conmon::rpc: 74: Got a create container request …
```
> Add OOM integration test

- .github/workflows/ci.yml
- scripts/get
/kind ci
This allows us verifying that the signature actually exist.
None
None
```release-note
None
```
> Install cosign for `get-script` CI step

- conmon-rs/server/src/server.rs
/kind cleanup
We now run try_init() on the log driver initialization which allows us
to catch the error.
Beside this, we now also do not pass `&self` to `init_self()` as well as
rename it to `init()`.
None
None
```release-note
None
```
> Run `try_init()` rather than `init()` which can panic

- .github/workflows/ci.yml
- .golangci.yml
- Makefile
/kind ci
Update the linter configuration as well as the tool to its latest version.
None
None
```release-note
None
```
> Update golangci-lint and config

- .github/workflows/ci.yml
- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/container_io.rs
/kind ci
Update the latest Rust toolchain version to the most recent release.
None
None
```release-note
None
```
> Bump Rust toolchain to v1.62.0

- .github/workflows/ci.yml
- .gitignore
- Makefile
- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/oom_watcher.rs
- conmon-rs/server/src/server.rs
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/suite_test.go
/kind ci
To make the CI more reliable.
None
Fixes https://github.com/containers/conmon-rs/issues/342
```release-note
None
```
> Make integration tests run more stable

- conmon-rs/server/src/config.rs
/kind cleanup
Copying the `bool` is more convenient than passing a `&bool` reference around.
None
None
```release-note
None
```
> Use `get_copy` for `--skip-fork` flag

- .golangci.yml
/kind ci
This helps to quick-fix the lint CI.
None
None
```release-note
None
```
> Increase cognitive complexity to 30

- conmon-rs/server/src/container_io.rs
/kind cleanup
To address CVE-2022-1708 we now limit the amount of output in an exec sync request to pre-defined `16 * 1024 * 1024` bytes.
Fixes https://github.com/containers/conmon-rs/issues/456
```release-note
Limit the amount of output in an exec sync request to pre-defined `16 * 1024 * 1024` bytes.
```
> Limit exec sync output len

- conmon-rs/server/src/cri_logger.rs
/kind cleanup
There is the corner case that the `usize` overflows when calculating `bytes_written + bytes_to_be_written`, which is now correctly handled.
None
None
```release-note
None
```
> Check for usize overflow in CRI logger

- conmon-rs/server/src/cri_logger.rs
/kind bug
We should account the bytes written globally and not on a per `write` basis. Added a unit test for the erroneous behavior.
None
None
```release-note
Fixed CRI logger max size behavior.
```
> Fix CRI logger max size behavior

- conmon-rs/server/src/attach.rs
- conmon-rs/server/src/container_io.rs
- conmon-rs/server/src/rpc.rs
/kind cleanup
Attach can rely on broadcast channels as well as having dedicated tasks for reading and writing to the UNIX sockets. This allows us to drop the tick interval in container_io.
None
None
```release-note
None
```
> Simplify attach handling

- go.mod
- go.sum
- pkg/client/suite_test.go
Pinning the golang deps to their latest release to let dependabot pickup new versions.
None
None
```release-note
None
```
> Pin `containers/*` dependencies

- .github/workflows/release.yml
- .gitignore
- Cargo.lock
- Makefile
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/main.rs
Adds release packaging workflows.
```release-note
NONE
```
> add release packaging

- .github/workflows/release.yml
I'm going to merge this to fix the release.yml.
> add dollar sign to release.yml

- Makefile
> add install target

- go.mod
- go.sum
- internal/proto/conmon.capnp.go
- pkg/client/attach.go
- pkg/client/client.go
Fixes #609
```release-note
NONE
```
Signed-off-by: Ryan Phillips <rphillips@redhat.com>
> bump capnproto to alpha.5

- README.md
The create has been renamed so we should adapt the docs link as well.
None
None
```release-note
None
```
> Fix rust docs link

- .github/workflows/ci.yml
- conmon-rs/server/src/terminal.rs
Unfortunately we skipped all unit tests within the CI which also makes it impossible to collect the code coverage. This is now fixers.
None
None
```release-note
None
```
> Run unit tests

- README.md
Adding a badge to link the package builds for `main`.
None
None
```release-note
None
```
> Add copr badge to link packages

- conmon-rs/client/Cargo.toml
- conmon-rs/common/Cargo.toml
- conmon-rs/server/Cargo.toml
/kind cleanup
Updating the version to v0.2.0 because we already released v0.1.0.
None
None
```release-note
None
```
> Bump to v0.2.0

- conmon-rs/server/src/oom_watcher.rs
/kind ci
This should fix the build on 32bit Linux platforms.
Refers to https://github.com/containers/conmon-rs/issues/675
None
```release-note
None
```
> Fix 32bit build

- .github/workflows/ci.yml
- .github/workflows/cross.yml
- Cross.toml
- conmon-rs/server/src/oom_watcher.rs
/kind ci
This change adds cross compilation tests for all supported copr builds to catch errors before merging.
Refers to #675 
Requires https://github.com/containers/conmon-rs/pull/688
```release-note
None
```
> Add cross compile tests

- conmon-rs/server/src/oom_watcher.rs
/kind cleanup
I was unable to debug an error message because of missing context. We now add more context to the messages as well as make the regex captures more save.
None
None
```release-note
None
```
> Make oom watcher errors more verbose

- pkg/client/client_test.go
/kind bug
The test unveils a memory leak in Exec Sync without providing a fix yet.
None
None
```release-note
None
```
> Add memory leak integration test for Exec Sync

- conmon-rs/server/src/oom_watcher.rs
/kind cleanup
For short lived containers we will mostly fail to watch for OOMs because the cgroup path does not exist any more. In that case we stop the watcher without erroring out to reduce the log verbosity.
None
None
```release-note
None
```
> Allow missing OOM watcher cgroup paths

- conmon-rs/server/src/rpc.rs
As per discussion in https://github.com/containers/conmon-rs/pull/683#discussion_r965889125, the TODO is already resolved.
None
None
```release-note
None
```
> Remove resolved TODO FIXME

- Makefile
/kind ci
```release-note
none
```
> make: add TEST_FLAGS to ginkgo tests

- conmon-rs/server/src/attach.rs
- conmon-rs/server/src/container_io.rs
- conmon-rs/server/src/rpc.rs
- conmon-rs/server/src/streams.rs
As well as add some comments on the new select! statements describing why they need to be there
/kind cleanup
```release-note
none
```
> attach: use Message::Done instead of cancellation token

- conmon-rs/server/src/attach.rs
/kind feature
This patch allows having multiple attach sessions in parallel by re-using the already existing attach socket.
Refers to https://github.com/containers/conmon-rs/issues/706
This does not solve the attach socket cleanup, which probably should happen on container removal.
```release-note
Allow having multiple attach sessions in parallel to the same container.
```
> Allow having multiple attach sessions in parallel

- conmon-rs/server/src/attach.rs
/kind bug
The conformance CRI test does not stop the running container after checking its output. It expects that the connection gets dropped when there is no more input to read. We now adjust the current attach behavior to stop in that case, which hopefully does not break the Podman use case.
See: https://github.com/kubernetes-sigs/cri-tools/blob/909f652/pkg/validate/streaming.go#L266-L305
We also strip down the size of the data packets to return the right amount of received bytes in the client.
A debug message has been changed which correctly logs the amount of written packets.
None
None
```release-note
Fixed critest "runtime should support attach" test.
```
> Fix critest "runtime should support attach" test

- Makefile
Signed-off-by: Peter Hunt~ <pehunt@redhat.com>
/kind other
```release-note
add `v` to release tag, as in `v0.0.0`
```
> release: add 'v' to the release tag

- .github/workflows/ci.yml
- .github/workflows/cross.yml
- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- Makefile
- conmon-rs/server/Cargo.toml
as we need it to build on RHEL 8
```release-note
Downgrade packages to support MSRV 1.58.0
```
> Build with 1.58.1

- conmon-rs/client/Cargo.toml
- conmon-rs/common/Cargo.toml
- conmon-rs/server/Cargo.toml
Signed-off-by: Peter Hunt~ <pehunt@redhat.com>
/kind other
```release-note
none
```
> bump to v0.3.0

- Makefile
/kind other
```release-note
none
```
> release: fix location of v

- Cargo.lock
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/config.rs
- conmon-rs/server/src/server.rs
Updating clap to the latest v3 and enabling the deprecated feature.
None
None
```release-note
None
```
> Update clap to v3.2.22

- Cargo.lock
- conmon-rs/client/Cargo.toml
- conmon-rs/common/Cargo.toml
- conmon-rs/server/Cargo.toml
Update to v0.4.0.
None
None
```release-note
None
```
> Bump to v0.4.0

- README.md
Signed-off-by: utam0k <k0ma@utam0k.jp>
Just fix a wrong link
NONE
```release-note
NONE
```
> Fix the link in README.md

- README.md
- conmon-rs/server/src/lib.rs
- release.md
- usage.md
None
We require a new CRI-O v1.25.2 to be released including the backport for conmon-rs v0.4.0: https://github.com/cri-o/cri-o/pull/6359
```release-note
Added usage documentation.
```
> Add usage/release documentation

- pkg/client/suite_test.go
It looks like that ginkgo now adds an additional go routine to the stack after the latest release. This should fix the integration tests.
None
None
```release-note
None
```
> Bump go routines to `7`

- .github/workflows/ci.yml
- Makefile
- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/listener.rs
- conmon-rs/server/src/oom_watcher.rs
- conmon-rs/server/src/server.rs
- conmon-rs/server/src/version.rs
/kind ci
Fix some lints not covered by our CI because we use an older toolchain there. We now use `nightly` within the CI as well as fixed the lints.
None
None
```release-note
None
```
> Fix latest `nightly` clippy lints

- Cargo.lock
- conmon-rs/client/Cargo.toml
- conmon-rs/common/Cargo.toml
- conmon-rs/server/Cargo.toml
Update to v0.5.0.
None
None
```release-note
None
```
> Bump to v0.5.0

- .github/workflows/ci.yml
- .github/workflows/release.yml
/kind ci
None
None
```release-note
None
```
> Switch to go 1.19 in CI

- .github/workflows/ci.yml
- .github/workflows/release.yml
- dependencies.yaml
/kind ci
Update CI jobs to use go 1.20.
None
None
```release-note
None
```
> Switch to go 1.20 for CI jobs

- .packit.yaml
Links to rhcontainerbot/podman-next for main branch builds.
None
None
```release-note
None
```
> [CI:DOCS] Packit: include ref to main branch builds

- conmon-rs/client/Cargo.toml
- conmon-rs/common/Cargo.toml
- conmon-rs/server/Cargo.toml
Update Cap'n Proto proto to the latest 0.14.x release.
None
None
```release-note
None
```
> Update Cap'n Proto to v0.14.11

- conmon-rs/client/Cargo.toml
- conmon-rs/common/Cargo.toml
- conmon-rs/server/Cargo.toml
/kind feature
Bump a new release version.
None
None
```release-note
None
```
> Bump to v0.5.1

- Makefile
- dependencies.yaml
/kind cleanup
Update zeitgeist to the latest release.
None
None
```release-note
None
```
> Update zeitgeist to v0.4.1

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Cargo.lock
- conmon-rs/client/Cargo.toml
- conmon-rs/common/Cargo.toml
- conmon-rs/server/Cargo.toml
- dependencies.yaml
/kind cleanup
Upgrade Rust to the latest available release.
Fixes https://github.com/containers/conmon-rs/issues/1231
None
```release-note
Switched to Rust v1.66.1.
```
> Switch to Rust v1.66.1

- Cargo.lock
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/config.rs
Update clap to the latest release.
None
None
```release-note
None
```
> Switch to clap v4

- conmon-rs/server/src/journal.rs
- conmon-rs/server/src/server.rs
/kind ci
Fixing the latest clippy reports.
None
None
```release-note
None
```
> Fix clippy lints

- Cargo.toml
/kind ci
The initial goal was to exclude the debug symbols, not to include them.
None
None
```release-note
None
```
> Set release build debug flag to `0`

- Cargo.lock
- conmon-rs/server/Cargo.toml
/kind cleanup
Update clap to the latest release.
None
None
```release-note
None
```
> Update clap to v4.3.8

- Makefile
- dependencies.yaml
/kind ci
The CI complains about the version mismatch. 
None
None
```release-note
None
```
> Update ginkgo to v2.11.0

- conmon-rs/client/Cargo.toml
- conmon-rs/common/Cargo.toml
- conmon-rs/server/Cargo.toml
/kind cleanup
There are a bunch of changes between 0.5.1 and main: https://github.com/containers/conmon-rs/compare/v0.5.1...main
None
/hold
For discussion.
```release-note
None
```
> Bump to 0.6.0

- .github/workflows/ci.yml
- Cargo.lock
/kind ci
This allows to detect possible required changes to Cargo.lock, for example when bumping the crate version.
None
Requires https://github.com/containers/conmon-rs/pull/1664
```release-note
None
```
> Check for `git diff` after build

- scripts/get
/kind cleanup
We should print the right environment variable for the architecture and also use the right fallback.
None
None
```release-note
None
```
> Fix get script architecture

- Cargo.lock
- conmon-rs/client/Cargo.toml
- conmon-rs/common/Cargo.toml
- conmon-rs/server/Cargo.toml
/kind cleanup
Bump to v0.6.1
None
Needs https://github.com/containers/conmon-rs/pull/1683 and https://github.com/containers/conmon-rs/pull/1682
```release-note
None
```
> Bump to v0.6.1

- conmon-rs/server/src/oom_watcher.rs
/kind cleanup
```
--> conmon-rs/server/src/oom_watcher.rs:152:9
|
152 | /         loop {
153 | |             tokio::select! {
154 | |                 _ = token.cancelled() => {
155 | |                     debug!("Loop cancelled");
...   |
169 | |             }
170 | |         }
| |_________^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#never_loop
= note: `#[deny(clippy::never_loop)]` on by default
```
None
None
```release-note
None
```
> Fix loop which never actually loops

- .github/workflows/ci.yml
/kind ci
We need to checkout the code before attempting to create the version marker. :upside_down_face: 
None
None
```release-note
None
```
> Add checkout to create marker

- Makefile
- dependencies.yaml
/kind ci
Update the ginkgo version to match the latest one in CI. 
None
None
```release-note
None
```
> Update ginkgo to v2.12.0

- conmon-rs/server/src/pause.rs
- conmon-rs/server/src/version.rs
/kind ci
Reporting the clippy lint issue.
None
None
```release-note
None
```
> Fix clippy lint

- .github/setup
Fixing the script location after its removal.
None
None
```release-note
None
```
> Fix CRI-O get script location

- .github/workflows/ci.yml
- .golangci.yml
- Makefile
- dependencies.yaml
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/suite_test.go
/kind ci
Update the linter and its configuration.
None
None
```release-note
None
```
> Update golangci-lint to v1.55.0

- .github/workflows/ci.yml
- .github/workflows/release.yml
- dependencies.yaml
/kind ci
This should be good to go, we have rust v1.71.0 in EL8/9.
None
None
```release-note
None
```
> Update min rust version to v1.71.0

- Cargo.lock
- conmon-rs/client/Cargo.toml
- conmon-rs/client/src/main.rs
- conmon-rs/common/Cargo.toml
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/capnp_util.rs
- conmon-rs/server/src/container_log.rs
- conmon-rs/server/src/rpc.rs
- conmon-rs/server/src/server.rs
Fixes #1688
I would appreciate if you tell me a better way to unwrap text_list without collect twice (see macros in rpc.rs). 
```release-note
None
```
> Bump capnp to 0.19.2

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .golangci.yml
- Makefile
- dependencies.yaml
- pkg/client/client.go
- pkg/client/remote_fds.go
- pkg/client/suite_test.go
/kind ci
Updating the dependencies within this repository.
None
None
```release-note
None
```
> Bump golang, linter and other third party deps

- Cargo.lock
- conmon-rs/client/Cargo.toml
- conmon-rs/common/Cargo.toml
- conmon-rs/server/Cargo.toml
/kind cleanup
Bump to v0.6.2.
None
None
```release-note
None
```
> Bump to v0.6.2

- .packit.yaml
CentOS 8 Stream will be frozen end of May, so no new stuff is expected to be shipped there.
EL8 jobs have been removed from the podman-next copr as well.
removes EL8 packit jobs
None
```release-note
None
```
> Packit: remove EL8 jobs

- .github/workflows/ci.yml
- dependencies.yaml
/kind ci
The latest nightly is incompatible with our dependency requirement, means we now use an older pinned nightly.
None
None
```release-note
None
```
> Downgrade toolchain for clippy and unit tests

- conmon-rs/server/src/child_reaper.rs
/kind cleanup
Helps to see the actual runtime command for debugging purposes.
None
None
```release-note
Added runtime command to debug output.
```
> Add runtime command to debug output

- .github/workflows/ci.yml
- .golangci.yml
- Makefile
- dependencies.yaml
- pkg/client/capnp_util.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/remote_fds.go
- pkg/client/suite_test.go
/kind cleanup
Update the linter config and fix new lints.
None
None
```release-note
None
```
> Update golangci-lint and fix lints

- conmon-rs/server/src/rpc.rs
/kind cleanup
Fixing a small borrow.
None
None
```release-note
None
```
> Fix borrowed expression which implements trait

- Cargo.lock
- conmon-rs/client/Cargo.toml
- conmon-rs/common/Cargo.toml
- conmon-rs/server/Cargo.toml
/kind cleanup
Update to the next release.
None
None
```release-note
None
```
> Bump to v0.6.4

- nix/default-s390x.nix
- nix/derivation.nix
/kind ci
This allows to output the `tag` and `commit` in `conmonrs --version`.
None
None
```release-note
Fixed `conmonrs --version` output for static builds to include the `tag` and `commit` fields.
```
> Add `gitMinimal` nix build dependency

- Cargo.lock
- conmon-rs/client/Cargo.toml
- conmon-rs/common/Cargo.toml
- conmon-rs/server/Cargo.toml
/kind cleanup
Update to the next release.
None
None
```release-note
None
```
> Bump to v0.6.5

- .github/workflows/ci.yml
/kind ci
Fixing the permission denied in critest CI.
None
None
```release-note
None
```
> Chown cache before installing ginkgo

- .github/workflows/gh-pages.yml
/kind ci
It does not work for vendoring, so we build the docs right ahead. 
None
None
```release-note
None
```
> Don’t generate lockfile for gh-pages workflow

- .github/workflows/cargo-upgrade.yml
- .gitignore
/kind ci
Add job to periodically upgrade the cargo dependencies.
None
None
```release-note
None
```
> Add cargo dependency update job

- .github/workflows/cargo-upgrade.yml
/kind ci
Keeping things simple and only use cargo-edit.
None
None
```release-note
None
```
> Don't run `cargo update`

- OWNERS
- OWNERS_ALIASES
/kind cleanup
Syncing the CRI-O owners as opt-in.
None
None
```release-note
None
```
> Add CRI-O OWNERS

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .golangci.yml
- Makefile
- dependencies.yaml
- go.mod
- pkg/client/suite_test.go
Update to the latest golang and golangci-lint.
None
None
```release-note
None
```
> Switch to go 1.23

- .github/dependabot.yml
- .github/workflows/cargo-upgrade.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .golangci.yml
- .prettierignore
- Makefile
/kind ci
Add a prettier target and apply the diff.
None
None
```release-note
None
```
> Add prettier CI target

- .github/workflows/cargo-upgrade.yml
- .github/workflows/ci.yml
- .github/workflows/cross.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
/kind ci
Pin the used GitHub actions.
None
None
```release-note
None
```
> Pin GitHub actions dependencies

- conmon-rs/server/src/child_reaper.rs
/kind bug
We can call waitpid on the process to reparent and ensure no zombies are left behind.
Fixes https://github.com/containers/crun/issues/1482
Fixes https://github.com/containers/conmon-rs/issues/2242
None
```release-note
Fixed issue that containers cannot be removed if init command was not found.
```
> Run waitpid on childs to ensure no zombies are left behind

- conmon-rs/server/src/child_reaper.rs
/kind cleanup
This helps to increase the verbosity around error handling.
None
None
```release-note
None
```
> Print child ID and error if command failed

- Cargo.lock
- conmon-rs/client/Cargo.toml
- conmon-rs/common/Cargo.toml
- conmon-rs/server/Cargo.toml
/kind cleanup
Update to the next release.
None
None 
```release-note
None
```
> Bump to v0.6.6

- .github/workflows/ci.yml
/kind ci
This allows using `go.sum` for caching.
None
None
```release-note
None
```
> ci: checkout before go setup

- .github/workflows/ci.yml
- dependencies.yaml
/kind ci
Move back to the latest nightly toolchain.
None
None
```release-note
None
```
> Switch to latest `nightly` toolchain

- .github/workflows/cargo-upgrade.yml
- .github/workflows/ci.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
/kind ci
The actions-rs actions are not maintained any more.
None
None
```release-note
None
```
> Replace actions-rs GitHub actions

- Cargo.lock
- conmon-rs/client/Cargo.toml
- conmon-rs/common/Cargo.toml
- conmon-rs/server/Cargo.toml
/kind ci
This bumps the development version to indicate new features.
None
None
```release-note
None
```
> Bump version to v0.7.0

- OWNERS_ALIASES
/kind other
https://github.com/cri-o/cri-o/issues/9314
```release-note
None
```
> Add @bitoku as reviewer

- pkg/client/client.go
/kind feature
This allows to retrieve the server version as struct type without requiring a running server. Can be used in CRI-O config validation for example.
None
None
```release-note
Added client `Version()` API to retrieve the server version without requiring a running instance.
```
> Add server `Version()` client API
