containers/conmon-rs

- Cargo.lock
- Cargo.toml
I think we wanted to get rid of the glib dependency, so we can remove it
from the crate as well. We now also bump the dependencies by using their
exact version number, they're still locked via Cargo.lock.
> Bump dependencies and remove glib

- src/server.rs
We now add logging support via env_logger. This allows using the log
macros, for example `info!()` and prints useful debugging information
side by side to the log message:
```
[2021-11-05T09:58:18.590Z INFO  conmon_server src/server.rs:75] Got a request: Request { metadata: MetadataMap { headers: {"te": "trailers", "content-type": "application/grpc", "user-agent": "tonic/0.6.1"}  }, message: VersionRequest, extensions: Extensions  }
```
> Add logging support

- src/config.rs
- src/server.rs
Before applying this patch the function was basically unused.
> Validate config before server start

- Cargo.lock
- Cargo.toml
- src/client.rs
- src/server.rs
This saves more than 50% RSS memory on runtime.
Before:
```
> cat /proc/(pidof conmon-server)/status | rg RSS
VmRSS:      3264 kB
```
After:
```
> cat /proc/(pidof conmon-server)/status | rg RSS
VmRSS:      1460 kB
```
Way better than: https://github.com/containers/conmon-rs/pull/8
> Switch to single threaded tokio runtime

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/server.rs
- tests/integration.rs
This should reduce the RSS memory usage and keep it constant over time
while logging.
Fixes https://github.com/containers/conmon-rs/issues/19
> Switch to simple-logger

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/server.rs
- tests/integration.rs
A key aspect of conmon is that it runs independent of the parent that calls it. As such, we need to daemonize. To be able to be tracked by the parent, we also need to write the new child's pid to a file that the parent specifies, so it can be watched.
Interestingly, the RSS is greatly reduced when we do this:
```
$ ./target/release/conmon-server --runtime /usr/bin/crun --conmon-pidfile=/tmp/pidfile
2021-11-12 14:41:28,540 INFO [conmon_server] Set log level to INFO
2021-11-12 14:41:28,540 INFO [conmon_server::init] Missing sufficient privileges to adjust OOM score
[pehunt@ovpn-114-123 conmon-rs(fork)]
$ cat /proc/$(pidof conmon-server)/status | grep RSS
VmRSS:       248 kB
[pehunt@ovpn-114-123 conmon-rs(fork)]
$ ./target/release/conmon-client --runtime /usr/bin/crun …
```
> server: daemonize and write pidfile

- .github/workflows/ci.yml
- Cargo.lock
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/init.rs
- conmon-rs/server/src/lib.rs
To be able to test the init functions, we require a wrapping structure
and replace-able implementation for it. This has been now added, while
the default init implementation is being used from the server.
> Add unit tests to init module

- conmon-rs/server/src/config.rs
This causes a runtime panic on server startup.
> Fix double usage of `-r` flag

- .github/workflows/ci.yml
- conmon-rs/client/Cargo.toml
- conmon-rs/common/Cargo.toml
- conmon-rs/server/Cargo.toml
to make sure we're compatible with slow-moving distros
heavily based off of https://github.com/ostreedev/ostree-rs-ext/pull/173/ thanks @lucab
> ci: build against Minimum Supported Rust Version

- .github/workflows/ci.yml
- pkg/client/client_test.go
- pkg/client/files_test.go
We now cache the integration test files as well as increase the timeout
for their retrieval.
> Cache integration test files

- conmon-rs/server/src/child_reaper.rs
We do not need to clone it twice hence one of them can be removed before
moving it into the thread.
> Remove unnecessary arc clone

- Cargo.lock
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/config.rs
- conmon-rs/server/src/lib.rs
We disconnect the stdout/err streams from conmon at a certain point of
execution. Therefore it would make more sense to log to a dedicated
driver instead of those streams. We now add a `--log-driver` option as
well as a default systemd logger.
> Add systemd logger

- conmon-rs/server/src/rpc.rs
Making the helper function a bit more idiomatic Rust.
> Make `path_vec_from_text_list` more idiomatic

- .github/workflows/ci.yml
- Makefile
This allows us to re-use the pre-built binary in other projects, like CRI-O.
> Add static release build artifact

- .github/workflows/ci.yml
- .github/workflows/gh-pages.yml
- Cargo.lock
- conmon-rs/server/Cargo.toml
- conmon-rs/server/build.rs
- conmon-rs/server/src/config.rs
- conmon-rs/server/src/lib.rs
This makes identifying the build binary easier, especially when pulling
it from CI artifacts.
Example run:
```
> cargo run --bin conmon-server -- -v
version: 0.1.0
tag: none
commit: 620d26869988905e716cfe7e4a1c444be3d21e02
build: 2022-02-10 09:42:37 +01:00
rustc 1.58.1 (db9d1b20b 2022-01-20)
```
> Add more verbose version information

- .github/workflows/ci.yml
- Cargo.lock
- Makefile
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/main.rs
- pkg/client/client.go
The proposal is that we use `conmon` for the server binary and bump the development version to v3.0.0.
> Rename `conmon-server` to `conmon` (v3.0.0)

- Cargo.lock
- conmon-rs/server/src/config.rs
CRI-O's conmon version parsing fails right now there:
https://github.com/cri-o/cri-o/blob/2e81aea6aa5d7a2fab42c07cfbe7a3f6299cea23/internal/config/conmonmgr/conmonmgr.go#L35-L37
To fix that, we now prepend the crate name to the version output.
> Make `conmon --version` CRI-O compatible

- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/lib.rs
- conmon-rs/server/src/rpc.rs
We now handle error paths which used `unwrap` before.
> Don't use `.unwrap()` any more

- Cargo.lock
- conmon-rs/server/Cargo.toml
We have been excluded it from dependabot, not sure how to re-enable it.
> Update clap to v3.1.5

- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/console.rs
- conmon-rs/server/src/lib.rs
- conmon-rs/server/src/rpc.rs
- pkg/client/client_test.go
Some errors can actually be returned or mapped by using the convenience
macro. We also fix a test name for the integration tests.
> Fix error handling paths

- .github/workflows/ci.yml
We also bump the toolchain to v1.59.0.
> Run integration tests on stable toolchain

- pkg/client/files_test.go
To avoid more flaky tests we now use our own Google Cloud bucket for the
test binary rather than the official sources which often timeout.
> Use cri-o bucket for busybox test binary

- conmon-rs/server/src/child_reaper.rs
as conmon currently does.
Also, handle WaitStatus::Signaled
> server: kill pgid if found

- .github/workflows/ci.yml
- Cargo.lock
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/version.rs
Since the binary name changed, we now can go back to an unreleased version.
> Move version back to v0.1.0

- Cargo.lock
- conmon-rs/client/Cargo.toml
Changes the conmon client to be conmonrs-cli to be more consistent with the server name.
Signed-off-by: Ryan Phillips <ryan@trolocsis.com>
> change client name to be conmonrs-cli

- conmon-rs/server/src/child.rs
- conmon-rs/server/src/child_reaper.rs
This makes required clones more visible, for example for the map
insertion.
> Use getset for `Child`

- conmon-rs/server/src/rpc.rs
as doing so will confuse clients who use the exit path as a signal that the container itself has exited
> exec: do not write to exit paths of container

- .github/workflows/ci.yml
- Makefile
- pkg/client/client_test.go
so users are able to run the integration tests without building statically
> add integration-static target

- conmon-rs/server/src/child_reaper.rs
- pkg/client/client_test.go
and add a TODO to gather the stdout from the runtime if it failed
> create_child: return error if runtime command failed

- conmon-rs/server/src/config.rs
- conmon-rs/server/src/container_io.rs
- conmon-rs/server/src/rpc.rs
- conmon-rs/server/src/server.rs
- conmon-rs/server/src/terminal.rs
- pkg/client/client.go
- pkg/client/client_test.go
This way, we know a conmon-rs's files are cleaned up after its runtime dir is
> client, server: add and use runtime dir instead of relying on temp files

- conmon-rs/server/src/config.rs
- conmon-rs/server/src/container_io.rs
- conmon-rs/server/src/lib.rs
- conmon-rs/server/src/listener.rs
- conmon-rs/server/src/rpc.rs
- conmon-rs/server/src/server.rs
- conmon-rs/server/src/terminal.rs
- pkg/client/client.go
- pkg/client/client_test.go
The runtime dir path will likely be the infra container's runDir, and thus something with a container UUID in it. Thus, it would be too long to hold the conmon.sock and work with the unix socket length. Work around this in the same way it was worked around in conmon (shout out to @giuseppe for coming up with the fix), where we use the `/proc/self/fd` entry of the parent directory of the target socket, and reference that when Dialing/Listening.
This also partially reverts https://github.com/containers/conmon-rs/pull/284, because for now runc doesn't support this functionality, so the process of receiving the console fd fails
> client, server: add support for very long server runtime dir paths

- conmon-rs/server/src/listener.rs
Just a small follow-up on: https://github.com/containers/conmon-rs/pull/310
> Use `Context` for `Option` type unwrapping

- README.md
We should point to the right repository for this link, which is now fixed.
> Fix README.md dependency link

- Makefile
- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/container_io.rs
- conmon-rs/server/src/rpc.rs
- conmon-rs/server/src/server.rs
- conmon-rs/server/src/streams.rs
- conmon-rs/server/src/terminal.rs
- pkg/client/client_test.go
as they fundamentally shouldn't be very different.
Also, drop stop_rx from streams impl, as it is racy, include https://github.com/containers/conmon-rs/pull/329 and update a message from child_reaper
> streams/terminal: unify read loop

- pkg/client/client_test.go
- pkg/client/suite_test.go
- create a suite_test file to reduce noise in client_test
- create a testRunner structure to drop global variables
- encapsulate common functionality into functions
- setup code for each test
- createContainer where we immediately also list to see if the container was created
- startContainer where we immediately also list to see if the container is running
> test: deduplicate code

- conmon-rs/common/proto/conmon.capnp
- conmon-rs/server/src/attach.rs
- conmon-rs/server/src/child.rs
- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/container_io.rs
- conmon-rs/server/src/rpc.rs
- conmon-rs/server/src/server.rs
- conmon-rs/server/src/streams.rs
- conmon-rs/server/src/terminal.rs
- go.mod
- go.sum
- internal/proto/conmon.capnp.go
- pkg/client/client.go
- pkg/client/client_test.go
This allows accessing everything via the `SharedContainerIO`.
Requires https://github.com/containers/conmon-rs/pull/340
> Move shared logger and attach into ContainerIO

- .github/workflows/ci.yml
- Makefile
We now re-use the pre-built binary in the integration tests to not build them multiple times,
> Reuse static binary in integration tests

- pkg/client/attach.go
- pkg/client/client_test.go
This allows that the values can be nil and makes the `Attach*` booleans obsolete.
> Wrap stdio in structs for attach

- pkg/client/attach.go
- pkg/client/client.go
A new configuration option allows to use a different logger rather than
the `logrus.StandardLogger()`.
> Make client logging configurable

- conmon-rs/server/src/version.rs
- pkg/client/client.go
We now return the full version result in the client.
> Make `Version()` return full result in golang client

- .golangci.yml
- pkg/client/attach.go
- pkg/client/client.go
- pkg/client/suite_test.go
We now enable the linters cyclop, gomnd, gosec and wrapcheck and fix their corresponding lints.
> Wrap errors and enable more linters

- conmon-rs/server/src/rpc.rs
The docs were missing from my previous patch, so we now ensure that this method has a docstring as well.
> Add docs to reopen container logs RPC

- README.md
- pkg/client/attach.go
- pkg/client/client.go
- pkg/client/consts.go
The whole client should be documented for godoc usage, which is now the case.
Kinda requires https://github.com/containers/conmon-rs/pull/370
> Document client

- .golangci.yml
- pkg/client/attach.go
- pkg/client/client.go
- pkg/client/suite_test.go
Enabling the excluded linter and pre-defining static errors while not exposing them to the API.
> Fix goerr113 lints

- .github/workflows/ci.yml
- Cargo.lock
- Makefile
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/child.rs
- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/lib.rs
- conmon-rs/server/src/oom_watcher.rs
- conmon-rs/server/src/rpc.rs
- conmon-rs/server/src/server.rs
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/suite_test.go
Added support for OOM detection. Need to figure out how to test it.
Fixes #297
> oom detection

- conmon-rs/server/src/server.rs
We do not have to expose it via the public API so we make it crate public again via getset.
> Make child reaper private again

- conmon-rs/server/src/server.rs
/kind cleanup
The returned type is private so the method is unusable anyhow. Since we
cannot set the configuration from the outside we now make it private to
lower the API surface.
None
None
```release-note
None
```
> Make server config private

- .github/workflows/ci.yml
- README.md
- scripts/get
/kind feature
We now sign the produced binary within the CI and push the artifacts to the release bucket. The `get` script is capable of verifying the signature if `cosign` if found as binary in `$PATH`.
None
None
```release-note
Automatically verify the `conmonrs` binary when using the `get` script if `cosign` is available in `$PATH`.
```
> Sign static binary

- .golangci.yml
- Makefile
- conmon-rs/server/src/attach.rs
- pkg/client/attach.go
/kind bug
We now indicate via a dedicated `DONE_PACKET` that we're finished writing all data, because we have no way to send `io.EOF` via the Rust API. This will fix the attach critest and allows the code paths to proceed.
Fixes https://github.com/containers/conmon-rs/issues/410
None
```release-note
Fixed critest case `runtime should support attach [Conformance]`
```
> Fix critest `runtime should support attach [Conformance]`

- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/rpc.rs
- pkg/client/client_test.go
/kind bug
This should fix the following CRI-O integration tests:
```
83 ctr create with non-existent command
84 ctr create with non-existent command [tty]
```
None
None
```release-note
Return OCI runtime error on container creation failure.
```
> Populate OCI runtime error if container create failed

- conmon-rs/server/src/container_io.rs
- conmon-rs/server/src/server.rs
- pkg/client/attach.go
/kind bug
Both loops do not block the read, especially when no attach session is happening right now or the container produces no output. We fix that behavior by polling every 100ms.
None
None
```release-note
Fixed busy loops for reading container IO.
```
> Fix IO busy loops

- conmon-rs/server/src/config.rs
- conmon-rs/server/src/server.rs
- pkg/client/client.go
/kind bug
We now can select a cgroup manager and set `--systemd-cgroup` on the OCI runtime level if systemd is selected (the default).
This fixes the passing of systemd related annotations to the config, for example: https://github.com/opencontainers/runc/pull/2224
None
None
```release-note
Using `--systemd-cgroup` for runtime commands.
```
> Add support for `--cgroup-manager`

- Cargo.lock
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/container_io.rs
- conmon-rs/server/src/streams.rs
- conmon-rs/server/src/terminal.rs
/kind bug
This removes the need for the tick interval for the `read_loop` and should also fix the failing critest suite.
None
None
```release-note
None
```
> Read asynchronously from stdout/err

- pkg/client/client.go
/kind feature
This allows easy type conversion between the log levels and avoids mismatches like "warn" (conmon-rs) and "warning" (logrus).
None
None
```release-note
Added `FromLogrusLevel` helper function.
```
> Add `FromLogrusLevel` helper

- Makefile
- conmon-rs.spec.rpkg
This commit includes a `conmon-rs.spec.rpkg` which along with a webhook
added to the conmon-rs repo will trigger automatic rpm builds on the
`rhcontainerbot/podman-next` copr repo.
With this change, a user can:
```
$ sudo dnf -y copr enable rhcontainerbot/podman-next
$ sudo dnf -y install conmon-rs
```
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
/kind other
Allows conmon-rs users to conveniently use the latest upstream features via rpms
None
Try running `make rpm` locally using this fork or try installing the package from the copr.
Successful build at: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/4703775/
f36 x86_64 rpm at: https://download.copr.fedorainfracloud.org/results/rhcontainerbot/podman-next/fedora-36-x86_64/04703775-conmon-rs/ …
> Autobuild Copr RPM after every PR merge

- conmon-rs/server/src/oom_watcher.rs
Should fix #603 
```release-note
fix cgroup2 super magic variable to be cross platform
```
> fix s390x and armhfp builds

- conmon-rs/server/Cargo.toml
/kind ci
v1.0.60 has been yanked from crates.io, which also makes gh-pages fail with:
```
error: failed to select a version for the requirement `anyhow = "^1.0.60"`
```
We now downgrade the version to fix failing builds.
None
None
```release-note
None
```
> Downgrade anyhow to fix gh-pages build

- conmon-rs/server/src/attach.rs
- conmon-rs/server/src/listener.rs
- conmon-rs/server/src/server.rs
- conmon-rs/server/src/terminal.rs
/kind cleanup
Increase the test coverage of the listener module by adding unit tests.
Part of #293 
None
```release-note
None
```
> Add listener unit tests

- conmon-rs/server/src/container_io.rs
- conmon-rs/server/src/streams.rs
/kind cleanup
Refers to #293 
None
None
```release-note
None
```
> Add streams unit test

- Makefile
- conmon-rs/server/src/attach.rs
- conmon-rs/server/src/child.rs
- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/container_io.rs
- conmon-rs/server/src/rpc.rs
- conmon-rs/server/src/streams.rs
- conmon-rs/server/src/terminal.rs
- pkg/client/attach.go
- pkg/client/client_test.go
- pkg/client/suite_test.go
/kind bug
Previously, the attach code was sending Done too early. This caused clients to detach early while there was still output to process. It previously used the "no output" condition to decide that there was no more output. However, it seems the read pipe will send `n == 0` (which I think should be looked into separately)
Really, the condition to stop the attach are two-fold: client detaches, or container exits. the former case should be handled. This PR adds the latter case by using a cancellation token and wiring it throughout the I/O code.
A followup should be checking that we're not CPU cycling when we get no output from the pipes (`n == 0` cases that were dropped) 
fixes https://github.com/containers/conmon-rs/issues/620
```release-note
Fix a bug where the server would detach …
```
> cancel I/O (notably attach) when container exits

- go.mod
- go.sum
- pkg/client/attach.go
- pkg/client/client.go
- pkg/client/suite_test.go
/kind bug
We now close outstanding `Read()` operations on `CopyDetachable` for each attach session. The conmon client collects all attach sessions and also closes them on `Shutdown`.
Fixes #534 
None
```release-note
Cleanup attach sessions to not leak any goroutine.
```
> Close attach readers

- Cargo.toml
- conmon-rs/server/src/attach.rs
/kind cleanup
It's unrealistic that we have to buffer 1000 packets, especially since they should be consumed by in a fast manner. We now still keep a safe zone of 4 packets in the channel, but this already reduces the memory by multiple hundred kilobytes.
We also optimize the release build by stripping of the binary as well as removing the debug symbols per default.
None
None
```release-note
None
```
> Reduce memory usage for attach

- Cargo.lock
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/config.rs
Update clap to the latest release, still ignored by dependabot.
None
None
```release-note
None
```
> Udpate clap to v3.2.21

- .github/setup
- .github/workflows/ci.yml
/kind ci
We now run a critest suite with a pinned CRI-O release for each PR.
None
Needs https://github.com/containers/conmon-rs/pull/702 to not timeout during the attach test.
```release-note
None
```
> Add critest run to CI

- pkg/client/client.go
/kind bug
We should not fail in case conmon-rs got killed by another instance, because this would trigger an error in sandbox removal in CRI-O and therefore makes it impossible to remove the sandbox. We now double check if the PID still exists before going into the wait loop.
None
None
```release-note
Fixed server shutdown error if PID does not exist any more.
```
> Fix server shutdown if conmon-rs got manually killed

- pkg/client/attach.go
- pkg/client/client.go
/kind feature
We cannot really know if the unix listener is still in use from the conmon-rs perspective, because it could be possible that conmonrs got killed while still having readers open on the client side.
We now add a cleanup logic to the client to remove the socket path if no readers are available any more. This allows conmonrs to still create multiple socket paths in parallel and keep them open until all clients are gone, the container terminates or the server does a shutdown.
Closes https://github.com/containers/conmon-rs/issues/706
None
None
```release-note
Cleanup unused attach sockets on the client side if all readers are dropped, the container exits or the server does a shutdown.
```
> Remove attach socket path if not in use

- conmon-rs/server/src/container_io.rs
/kind bug
The stream data is only read on `read_all_with_timeout`, which is called via exec sync or on on container creation error. This means we can end-up having a closed sender, but we should not fail in this case because it will lead into unexpected container termination.
Fixes https://github.com/containers/conmon-rs/issues/720
None
```release-note
Fixed bug where a closed stream sender causes container termination.
```
> Send only streams data if channel is not closed

- conmon-rs/server/src/container_io.rs
- conmon-rs/server/src/streams.rs
- conmon-rs/server/src/terminal.rs
- pkg/client/client_test.go
/kind bug
This allows the read loop to finish one there is nothing more to read.
Fixes #738 
This is fixing the GitHub actions e2e tests in CRI-O: https://github.com/cri-o/cri-o/actions/runs/3098295877/jobs/5017090180
```release-note
Fixed bug where read loop races with the container exit.
```
> Remove token from ContainerIO read_loop

- conmon-rs/server/src/attach.rs
- conmon-rs/server/src/container_io.rs
- pkg/client/attach.go
/kind bug
This fixes the first test of `should support inline execution and attach`:
https://github.com/kubernetes/kubernetes/blob/7f129f1c9af62cc3cd4f6b754dacdf5932f39d5c/test/e2e/kubectl/kubectl.go#L603-L612
Short lived attach sessions may have some more content to read after they exited, which is now fixed by trying another read after the token has been canceled via the waitpid exit.
Refers to https://github.com/containers/conmon-rs/issues/736
The `--leave-stdin-open=true` tests are still failing, but those have to be fixed in another PR:
https://github.com/kubernetes/kubernetes/blob/7f129f1c9af62cc3cd4f6b754dacdf5932f39d5c/test/e2e/kubectl/kubectl.go#L614-L648
```release-note
Fixed race between container exit and stdin attach data to be processed.
```
> Read once again after stdin token cancelled

- .github/workflows/ci.yml
/kind ci
Can be merged after https://github.com/cri-o/cri-o/pull/6220
None
None
```release-note
None
```
> Re-enable critest GitHub action

- conmon-rs/server/src/config.rs
- conmon-rs/server/src/server.rs
/kind api-change
This follows more idiomatic rust and makes the migration to clap v4 easier.
None
None
```release-note
Removed `VERSION_FULL` in favor of the `config::Verbosity` enum.
```
> Make version verbosity an enum

- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/consts.go
- pkg/client/suite_test.go
/kind api-change
This allows a better API usage by having native types around possible values. We also now rename the LogDriver for the container creation to `ContainerLogDriver` to be more distinct compared to the server log driver.
None
None
```release-note
Renamed the `LogDriver` for the container creation to `ContainerLogDriver` to be more distinct compared to the server log driver.
```
> Add native types for server `LogDriver` and `LogLevel`

- .github/install-deps
- .github/workflows/cross.yml
- .golangci.yml
- Cargo.lock
- Cross.toml
- conmon-rs.spec.rpkg
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/config.rs
- conmon-rs/server/src/init.rs
- conmon-rs/server/src/server.rs
- contrib/tracing/docker-compose.yaml
- contrib/tracing/otel-collector-config.yaml
- pkg/client/client.go
/kind feature
This allows using the GRPC endpoint of an OTLP exporter to export span-based telemetry data directly from conmon-rs.
Fixes #481 
**Demo:**
For usage with the current CRI-O `main` we have to manually force-enable tracing:
```diff
diff --git a/conmon-rs/server/src/config.rs b/conmon-rs/server/src/config.rs
index 98f99ed..f2b5ff2 100644
--- a/conmon-rs/server/src/config.rs
+++ b/conmon-rs/server/src/config.rs
@@ -113,6 +113,7 @@ pub struct Config {
env(concat!(prefix!(), "ENABLE_TRACING")),
long("enable-tracing"),
short('e'),
+        default_value("true"),
)]
/// Enable OpenTelemetry tracing.
enable_tracing: bool,
```
Then we can give it a try:
```
> cargo build
> cd contrib/tracing/ && docker-compose up
> cd /path/to/cri-o
> sudo crictl run test/testdata/container_redis.json …
```
> Add support for OpenTelemetry tracing via OTLP

- Cargo.lock
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/server.rs
/kind feature
This allows tracing multiple conmon-rs instances selectively  by their PID and host.
None
None
```release-note
Added `process.pid` and `host.name` to Open Telemetry traces.
```
> Add conmon-rs process ID and host name to tracing output

- conmon-rs/server/src/lib.rs
- conmon-rs/server/src/server.rs
- conmon-rs/server/src/telemetry.rs
- go.mod
- go.sum
/kind cleanup
This allows further enhancements to be encapsulated from the server implementation.
None
None
```release-note
None
```
> Move telemetry code into own module

- conmon-rs/server/src/server.rs
/kind bug
This makes the overall exporter race a bit more resilient against race conditions.
None
We still seem to miss the root spans in some cases, but the overall result for a container creation will now look like this, which is promising:
```release-note
None
```
> Shutdown tracing after runtime

- conmon-rs/server/src/server.rs
- pkg/client/client_test.go
/kind bug
According to https://github.com/open-telemetry/opentelemetry-rust/issues/888#issuecomment-1280052833, this works around the issue where the root span is missing from the traces.
None
```release-note
None
```
> Manually add OTEL context to both root spans

- pkg/client/attach.go
- pkg/client/client.go
/kind feature
If we now pass down a `trace.Tracer` via the configuration, conmonrs is able to add additional spans based on how the client is being used.
None
None
```release-note
Added `Tracer trace.Tracer` to the server configuration, which allows the client to create additional spans.
```
> Allow client traces by passing a tracer

- Cargo.lock
- conmon-rs/client/Cargo.toml
- conmon-rs/client/src/main.rs
I was looking at this code as an example of Rust + capnp, and was a bit surprised at the usage of the non-tokio networking crate.
In digging some, the server is already using the tokio compat bridges, so let's do the same on the client.
This drops out many duplicative dependencies.
> rust: Port client to use tokio too

- .github/workflows/ci.yml
Ubuntu 22.04 glibc static is not compatible with rustc 1.58.1 (see `ACTION_MSRV_TOOLCHAIN`). Means we now just use the latest one, since the static builds are made for the community.
Fixes #957
None
```release-note
Switched to latest rust stable for static binaries.
```
> Use `stable` toolchain for static build

- conmon-rs/server/src/attach.rs
- conmon-rs/server/src/container_io.rs
The Kubernetes e2e test flakes because of a token cancellation race between stdin and attach read:
```
[FAIL] [sig-cli] Kubectl client Simple pod [It] should support inline execution and attach
…
<< Timeline
[FAILED] Expected
<string>: read:stdin closed
to contain substring
<string>: read:value
In [It] at: test/e2e/kubectl/kubectl.go:764 @ 01/04/23 15:09:48.618
```
https://github.com/kubernetes/kubernetes/blob/5cbd6960c805c22e1c741dde3ce9f2e10f869bce/test/e2e/kubectl/kubectl.go#L757-L766
The issue is that we cancel the token immediately which stops reading from attach. But the container command `echo -n read: && cat && echo 'stdin closed'` within the test provides additional data, which gets no time to be delivered.
We now drain stdin accordingly and wait for all data …
> Drain stdin on attach

- conmon-rs/server/src/attach.rs
- conmon-rs/server/src/container_io.rs
Reverts containers/conmon-rs#991
This will not fix the problem and will make it even worse. We have to somehow split-up the cancellation tokens to wait for stdin and stdout/err separately.
> Revert "Drain stdin on attach"

- .golangci.yml
- Cargo.lock
- conmon-rs/common/proto/conmon.capnp
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/config.rs
- conmon-rs/server/src/lib.rs
- conmon-rs/server/src/pause.rs
- conmon-rs/server/src/rpc.rs
- conmon-rs/server/src/server.rs
- internal/proto/conmon.capnp.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/consts.go
/kind feature
This experiment adds support for running a global shared pause instance side by side to `conmonrs`. The idea is that this instance keeps the required namespaces open and provides them as part of the container creation response to the consumers.
Refers to https://github.com/containers/conmon-rs/issues/871
None
```release-note
TBD
```
> Add support for `pause`

- go.mod
- pkg/client/client.go
- pkg/client/consts.go
- pkg/client/errors.go
/kind feature
We now pre-check if conmon-rs supports the `CreateNamespaces` RPC and return a wrapped defined error if not.
Requires https://github.com/containers/conmon-rs/pull/1040
None
```release-note
Check supported version for `CreateNamespaces` RPC
```
> Check supported version for `CreateNamespaces` RPC

- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/oom_watcher.rs
/kind bug
It may be possible that the container process already got signaled but is still running, whereas we will not get a `modify` (but `other`) event on the file watcher. Beside that, it will also not update the `oom` entry of `memory.events`, but the `oom_kill`, which provides another indicator for a possible out of memory kill.
Ref: https://www.kernel.org/doc/Documentation/cgroup-v2.txt
Adresses https://github.com/cri-o/cri-o/issues/6580 for the conmon-rs usage 
None
```release-note
Fixed OOM detection for cgroup v2 edge-cases where the container already got signaled but has not been fully OOM killed.
```
> Fix OOM watcher for cgroupv2 `oom_kill` events

- conmon-rs/server/src/pause.rs
- pkg/client/client_test.go
/kind bug
We now bind all namespaces, independently if unshared or not. If a namespace is not being unshared, then we fallback to the host.
Required for https://github.com/cri-o/cri-o/pull/6590
None
```release-note
Fixed pinning all namespaces to the host when not selected for unsharing in `conmonrs pause`
```
> Bind missing namespaces to host

- .github/workflows/ci.yml
- Makefile
- dependencies.yaml
/kind ci
We now use a dedicated job for verifying our dependencies while pinning them in `dependencies.yaml`.
None
None
```release-note
None
```
> Use zeitgeist for dependency verification

- .github/workflows/ci.yml
- .golangci.yml
- Makefile
- dependencies.yaml
- pkg/client/client_test.go
- pkg/client/suite_test.go
/kind ci
The update to golangci-lint v1.51.1 fixes the ginkgolint panic. Therefore we can enable the linter and fix the reports.
None
None
```release-note
None
```
> Enable ginkgolint

- .packit.sh
- .packit.yaml
- conmon-rs.spec.rpkg
- conmon-rs/common/Cargo.toml
This commit will run COPR builds on every PR against all active releases of CentOS Stream and Fedora, thus allowing buildability checks before the PR merges.
Builds are done on a custom COPR project:
`rhcontainerbot/packit-builds`.
Ref: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/
The build targets are set in the copr itself, so we don't need to explicitly mention them in `.packit.yaml`, making upstream configuration a lot simpler.
The `spec.rpkg` file meant for rpm builds post-pr-merge at `rhcontainerbot/podman-next` copr gets reused for packit builds, so the packit jobs are independent of Fedora / CentOS dist-git.
Fixes: #1103
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
/kind ci
Checks for fedora and centos stream buildability pre-merge.
Fixes #1103 …
> [CI:BUILD] Packit: initial enablement

- .packit.sh
- conmon-rs.spec.rpkg
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
Fixed some packit comment nits :smile: 
None
None
```release-note
None
```
> [CI:DOCS] Packit: fix comments

- .packit.yaml
/kind ci
Enable packit builds for the main branch.
None
PTAL @lsm5 
```release-note
None
```
> Enable packit for `main` branch

- conmon-rs/server/src/pause.rs
/kind other
Typo fix in comment. Also helps to check if packit builds are triggered on rhcontainerbot/podman-next copr after commit on main branch.
None
None
```release-note
None
```
> [CI:DOCS] nit: fix typo

- conmon-rs/server/src/init.rs
- conmon-rs/server/src/server.rs
/kind feature
Under non-reproducible circumstances it can happen that the umask of conmon-rs is set to 0000, which can be a security issue. To avoid that, we now use a default umask and set it directly in the init module.
We had a similar fix in CRI-O in cri-o/cri-o#5904, but we have to do it here again because conmon-rs is a direct parent of PID 1.
Refers to https://issues.redhat.com/browse/OCPBUGS-8057
Proposing the same in conmon: https://github.com/containers/conmon/pull/388
```release-note
Using default umask of `0022` for all conmon-rs processes.
```
> Use default umask `0022`

- .github/workflows/ci.yml
It looks like that we can pass `-y` to omit the prompt in the CI script.
See https://github.com/containers/conmon-rs/actions/runs/4342656226/jobs/7583748919
None
```release-note
None
```
> Fix signing binary

- .packit.sh
Resolves: #1173
/kind other
Fixes rpm release tag in copr builds
#1173 
Fixes #1173 
None
```release-note
None
```
> Packit: Fix sed for release tag update in rpm spec

- .github/workflows/ci.yml
- conmon-rs/server/src/cri_logger.rs
- pkg/client/client.go
- pkg/client/client_test.go
/kind ci
We now verify any typos in CI and fix them.
None
None
```release-note
Fixed API typos in golang client.
```
> Check and fix typos in CI

- conmon-rs/server/src/oom_watcher.rs
Clippy complains about this on `main`.
None
None
```release-note
None
```
> Remove unrequired cfg `any` directive

- pkg/client/client.go
/kind cleanup
Merging of 22a1616 and c354aaf resulted in redundant serialization of the `OOMExitPaths` field.
Both commits introduced the `OOMExitPaths` field and added serialization code.
```release-note
None
```
> Remove redundant serialization of OOMExitPaths

- pkg/client/client.go
Mention in the documentation that the go client will connect to an already running server instance.
When a server is already listening in the same `ServerRunDir`, the client reuses that server.
That also means that other options of the `ConmonServerConfig` will be ignored. The server will keep its settings from the first invocation.
```release-note
None
```
> Mention that the go client reuses a running server

- .packit.yaml
The packit workflow for Podman and other repos has recently changed to include the official rpm spec file upstream and have Fedora dist-git sync from upstream on every release.
Ref: https://github.com/containers/podman/pull/18465
This has made it necessary to verify ELN package build success in our copr builds. And enabling ELN on copr is causing conmon-rs failures Ref: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/6121423/
Since ELN is not an immediate concern, this commit will only do copr builds for centos stream and fedora rawhide, 38 and 37.
/kind other
Disable ELN buildroot for copr builds
None
```release-note
None
```
> COPR: Exclude ELN builds

- .packit.yaml
The previous target was wrongly entered which ended up not triggering builds for centos-stream+epel-next-9-x86_64.
Ref: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/6125671/
/kind other
fixes a wrongly entered cop build target
None
None
```release-note
None
```
> Packit: Fix Copr target

- pkg/client/attach.go
- pkg/client/client.go
/kind cleanup
A capnp request created with `p.NewRequest()` is already associated with the params.
Therefore a call to `p.SetRequest(req)` is not necessary.
None
The `SetRequest` function was only used in 4 out of 7 requests. The others already work without this call.
```release-note
None
```
> Remove unnecessary SetRequest calls

- conmon-rs/server/src/child_reaper.rs
/kind bug
I think the retain condition in `ChildReaper::forget_grandchild` was flipped.
The function passed to retain specifies which elements to keep, but the specified condition returned which element we want to remove. ([docs](https://docs.rs/multimap/0.9.0/multimap/struct.MultiMap.html#method.retain))
That results in the removal of all `grandchildren` except the one we want to forget.
None
I assume that the `forget_grandchild` function should **remove** the grandchild with `pid == grandchild_pid` and not keep it.
There could be existing use cases that depend on the fact, that the ChildReaper forgot the wrong grandchildren by accident.
I'm not sure, but it could be the case that conmon-rs didn't terminate spawned childs on exit because of this and will do this now. This could be a …
> Fix forget_grandchild retain condition

- Cargo.lock
- conmon-rs/common/proto/conmon.capnp
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/capnp_util.rs
- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/lib.rs
- conmon-rs/server/src/telemetry.rs
- internal/proto/conmon.capnp.go
- pkg/client/attach.go
- pkg/client/capnp_util.go
- pkg/client/client.go
/kind other
Currently (if tracing is enabled) the `metadata` field gets filled with a JSON encoded string map, that contains tracing metadata.
This PR changes this and uses capnp native maps and thereby eliminates the double encoding of JSON data inside of a capnp struct. Note that the [_proper way_](https://capnproto.org/language.html#generic-types) to implement maps in capnp is to use a `List` of string tuples.
Changes:
- Rename the existing `metadata` field to `metadataOld`
- Add a new `metadata` field of type `List[StringStringMapEntry]`
- Add utility functions to convert between a `List` of `MapEntry`s and rust types
- Remove `serde_json` from the server code
- Move capnp util function in go to `capnp_util.go` (slice and map encoding)
- Encode the metadata in the client in both …
> Use capnp map for tracing metadata

- conmon-rs/server/src/container_io.rs
This fixes the redundant guard error:
```
error: redundant guard
--> conmon-rs/server/src/container_io.rs:246:26
|
246 |                 Ok(n) if n == 0 => {
|                          ^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_guards
= note: `-D clippy::redundant-guards` implied by `-D warnings`
help: try
|
246 -                 Ok(n) if n == 0 => {
246 +                 Ok(0) => {
|
```
None
None
```release-note
None
```
> Fix clippy lint

- .github/workflows/ci.yml
- .github/workflows/release.yml
- conmon-rs/server/Cargo.toml
- dependencies.yaml
/kind ci
We can also remove the build constraints from the `Cargo.toml` file since we have updated them in the past.
None
None
```release-note
Updated latest required Rust version to v1.69.0
```
> Bump Rust to v1.69.0

- .github/dependabot.yml
/kind ci
This allows dependabot to group dependency updates, which were required to be manually in PR's like https://github.com/containers/conmon-rs/pull/1551.
None
None
```release-note
None
```
> Add opentelemetry dependency group

- .github/typos.toml
- .github/workflows/ci.yml
- Cargo.lock
- Makefile
- conmon-rs/common/proto/conmon.capnp
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/child_reaper.rs
- conmon-rs/server/src/config.rs
- conmon-rs/server/src/fd_socket.rs
- conmon-rs/server/src/lib.rs
- conmon-rs/server/src/listener.rs
- conmon-rs/server/src/macros.rs
- conmon-rs/server/src/rpc.rs
- conmon-rs/server/src/server.rs
- internal/proto/conmon.capnp.go
- pkg/client/capnp_util.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/remote_fds.go
- pkg/client/suite_test.go
/kind feature
This PR adds support for file descriptors:
- New `StartFdSocket` RPC command
- `additionalFds` passed to the OCI runtime
- `leakFds` kept open by conmon as long as the container is running
I haven't found a good way to pass file descriptors via `SCM_RIGHTS` on the existing RPC connection. Therefore an additional socket is created for file descriptor passing. The protocol is documented in `conmon-rs/server/src/fd_socket.rs`.
RPC level workflow:
- The client calls `StartFdSocket` to start the fd socket server (if not already running) and gets the socket path
- The client send the file descriptors to the server via `SCM_RIGHTS` and gets slot numbers in return
- The client needs to keep the fd socket connection open until the fds are used
- The client calls `CreateContainer` …
> Add support for file descriptor passing

- pkg/client/attach.go
/kind cleanup
The `Resize` channel in the `AttachConfig` go struct was not restricted. This PR changes the channel to a receive only channel.
```diff
-	Resize chan resize.TerminalSize
+	Resize <-chan resize.TerminalSize
```
The channel is only used for receive operations.
**Note:** This is technically a breaking change as the following code would no longer work:
```go
config := new(client.AttachConfig)
config.Resize = make(chan resize.TerminalSize, 1)
config.Resize <- size
```
But this is an uncommon usage pattern. The following pattern is more expected (used by CRI-O) and is unaffected by this change:
```go
resize := make(chan resize.TerminalSize, 1)
resize <- size
config := new(client.AttachConfig)
config.Resize = resize
```
None
```release-note
None
```
> Change resize channel to receive only

- Cargo.lock
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/container_io.rs
- conmon-rs/server/src/streams.rs
- conmon-rs/server/src/terminal.rs
/kind bug
The `ContainerIO::read_loop_stdin` function was taking the fd to stdin as a `RawFd` and took ownership of the file descriptor. This worked for piped IO (`streams.rs`) but not for tty based IO (`terminal.rs`).
With tty based IO the same file descriptor was used as an `AsyncFd` and passed to `read_loop_stdin` this resulted in two owners of the same file descriptor. The first owner (stdin in most cases) would close the fd on drop. The second owner would stall as it won't be notified that the fd closed and once the second owner would drop it would try to close the same fd again. Which could have been reused in the meantime.
This change refactors `ContainerIO::read_loop_stdin` to take an implementation of `AsyncWrite` and introduces a new `TerminalFd` which wraps the pty file …
> Fix early stdio close due to multiple ownership

- .github/create-marker
- scripts/get
/kind bug
We have to specify the right git ref for cosign to let the script work correctly on tags.
None
None
```release-note
Fixed correct git ref usage for get script when being used on tags.
```
> Fix get script for tags

- Cargo.lock
- Cargo.toml
/kind ci
Cargo complains that the resolver is not set. We now default to v2 and update the lockfile.
None
None
```release-note
None
```
> Set resolver to v2

- .github/workflows/ci.yml
- .gitignore
- Makefile
- dependencies.yaml
- nix/default-amd64.nix
- nix/default-arm64.nix
- nix/default-ppc64le.nix
- nix/default.nix
- nix/derivation.nix
- nix/nixpkgs.json
- nix/nixpkgs.nix
- nix/overlay.nix
- nix/static.nix
/kind feature
Allow multi-arch statically linked binaries for amd64, arm64 and ppc64le.
None
None
```release-note
Added multi-arch static binaries for amd64, arm64 and ppc64le.
```
> Add nix build for multi-arch static binaries

- .github/workflows/ci.yml
- scripts/get
/kind feature
We now provide support for our new statically linked architectures.
None
None
```release-note
Add support for `amd64`, `arm64` and `ppc64le` as part of the `get` script.
```
> Add architecture support to `get` script

- pkg/client/remote_fds.go
/kind bug
Fixing the build for:
```
> GOARCH=386 go build ./...
pkg/client/remote_fds.go:101:15: invalid operation: numFDs == int64(1) << int64(numFDsBits) (mismatched types int and int64)
```
None
None
```release-note
Fixed constant int overflow for `GOARCH=386`.
```
> Fix constant int overflow for `GOARCH=386`

- scripts/get
/kind feature
This allows installing different conmon-rs architectures on the same machine.
None
None
```release-note
Added `-n` flag to get script to avoid binary execution.
```
> Add -n flag to get script to avoid binary execution

- .github/workflows/ci.yml
/kind ci
We now make a dedicated `create-marker` step which runs only if all static builds passed. Otherwise we'll risk that the get-script points to a non completed commit resulting in a 404.
None
None
```release-note
None
```
> Create marker only if CI passed

- Makefile
- pkg/client/suite_test.go
/kind ci
I assume that the recent runner image release causes the binary to consume more RSS:
https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230911.1
Nothing obvious has changed between the successfull and failing runs other than the runner image, so it could be also related to the kernel bump from `5.15.0-1041-azure` to `6.2.0-1011-azure`.
None
None
```release-note
None
```
> Bump max rss to 7500

- .github/setup
/kind ci
The `crio-status` binary got removed from the static binary bundles so we have to use `crio status` instead.
None
None
```release-note
None
```
> Switch to `crio status`

- Makefile
- dependencies.yaml
ginkgo version in make file wasn't matched with the version in go.mod.
It seems ginkgo version update is fast so it would be good to keep the version up to date by running `go list`.
None
```release-note
None
```
> make ginkgo version keep up to the version in go.mod

- .packit.yaml
/kind ci
EPEL is the recommended target for further testing with rpm builds.
cc @lsm5 
Similar to https://github.com/containers/podman/pull/22432
/hold
```release-note
None
```
> Packit: switch to EPEL instead of centos-stream+epel-next

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Cargo.lock
- conmon-rs/server/Cargo.toml
- conmon-rs/server/src/attach.rs
- conmon-rs/server/src/container_io.rs
- conmon-rs/server/src/server.rs
- dependencies.yaml
/kind feature
Downgrade dependencies to support Rust v1.66.1
Refers to https://issues.redhat.com/browse/OCPNODE-1986
None
```release-note
None
```
> Downgrade Rust to v1.66.1

- conmon-rs/common/src/lib.rs
- nix/default-s390x.nix
- nix/derivation.nix
- nix/overlay.nix
/kind bug
Building using musl until NixOS/nixpkgs#306473 is resolved.
Refers to cri-o/cri-o#7911
None
```release-note
Fixed s390x build using musl libc.
```
> Build s390x binaries using musl libc

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- Makefile
- go.mod
- go.sum
- pkg/client/client.go
When building the [go-capnp](https://github.com/capnproto/go-capnp) using Go 1.23 or Go tip, the following build error will be reported (an example build failure from the CRI-O project):
```console
vendor/capnproto.org/go/capnp/v3/list.go:1087:10: invalid composite literal type T
```
Thus, upgrade the go-capnp version to [v3.0.1-alpha.2](https://github.com/capnproto/go-capnp/releases/tag/v3.0.1-alpha.2), which would fix the build issue on a newer version of Go.
Related:
- https://github.com/capnproto/go-capnp/pull/576
- https://github.com/cri-o/cri-o/issues/8373
None
None
```release-note
None
```
> Update go-capnp package to fix build issue on Go 1.23

- conmon-rs/server/src/oom_watcher.rs
/kind bug
If the slice is already removed then we mostly encounter two different errors:
- `get next line: No such device (os error 19)`
- `open memory events file: /sys/fs/cgroup/test.slice/crio-$ID.scope/memory.events: No such file or directory (os error 2)`
To avoid such a race we now check after the errors if the file still exists. If not, then we assume an OOM.
Fixes https://github.com/cri-o/cri-o/issues/8411
None
```release-note
Fixed OOM slice removal race to not report an out of memory event.
```
> Fix OOM slice removal race

- Makefile
- release.md
/kind cleanup
We already vendor the sources so we do not have to do it multiple times.
None
None
```release-note
None
```
> Remove double vendored sources from release

- .github/dependabot.yml
/kind ci
Dependabot does not support vendored cargo, so we have to disable it for now.
None
None
```release-note
None
```
> Disable dependabot for Rust

- conmon-rs/server/src/config.rs
- pkg/client/client.go
/kind other
This PR changes the default tracing endpoint to 127.0.0.1 to align with the cri-o change.
Fixes a part of https://github.com/cri-o/cri-o/issues/7448
```release-note
Use 127.0.0.1 as the new default for tracing endpoint.
```
> Change default from localhost to 127.0.0.1

- conmon-rs/server/src/server.rs
/kind feature
We now support the new crun log level flags.
Refers to https://github.com/containers/crun/issues/1525
None
```release-note
Added support for crun log level flags, which requires at least crun v1.16.2.
```
> Add support for crun `--log-level`

- Makefile
/kind cleanup
Add a nice `make help` output like this:
```
Usage:
make <target>
help                       Display this help.
Build targets:
default                    Build in debug mode.
release                    Build in release mode.
release-static             Build the static release binary.
Test targets:
unit                       Run the unit tests.
integration                Run the integration tests using the release binary.
integration-static         Run the integration tests using the static release binary.
Verify targets:
lint                       Lint Rust and Go sources.
lint-rust                  Lint the Rust sources.
lint-go                    Lint the Go sources.
verify-dependencies        Verify the local dependencies.
verify-prettier            Run prettier on the …
```
> Add support for `make help`

- .packit.yaml
F39 builds have been disabled on the podman-next copr because of go1.22 bump on golang projects.
This can be set back to `fedora-all` once F39 goes EOL.
removes failing test for soon-to-be-EOL Fedora 39
Fixes #2428 
None
```release-note
None
```
> packit: remove f39

- conmon-rs/client/src/main.rs
- conmon-rs/server/src/lib.rs
- conmon-rs/server/src/telemetry.rs
/kind ci
The reported lints seems to be a false positive from nightly, means we now avoid that. We also fix the lifetime for the Metadata struct report.
None
None
```release-note
None
```
> Fix clippy lints

- conmon-rs/server/src/config.rs
- conmon-rs/server/src/server.rs
- conmon-rs/server/src/version.rs
/kind feature
Allowing to output the version in parsable JSON format.
None
None
```release-note
None
```
> Add `--version-json` flag for JSON version output

- scripts/get
/kind ci
We often hit 403 errors when running the get script in CI. To mitigate them, we now support the GITHUB_TOKEN environment variable and apply it correctly if required.
None
See: https://github.com/cri-o/packaging/actions/runs/16485668216/job/46609790928
```release-note
Added `$GITHUB_TOKEN` environment variable support to `get` script.
```
> Add GITHUB_TOKEN env support to get script

- conmon-rs/server/src/oom_watcher.rs
/kind bug
The `unwatch` call can deadlock in specifics cases which cause test flakes in our CI. We now work around this issue by stopping the unwatch and let conmon-rs terminate correctly.
Ref: https://github.com/notify-rs/notify/issues/463
None
```release-note
Stop conmon-rs from hanging when inotify unwatching blocks. 
```
> Fix deadlock when unwatching notify watchers
